name: YT Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Check cache
      run: |
        echo upstream_heads=`git ls-remote https://github.com/theos/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/theos/sdks | head -n 1 | cut -f 1` >> $GITHUB_ENV

    - name: Use cache
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/theos
        key: ${{ runner.os }}-${{ env.upstream_heads }}
    
    - name: Prepare Theos
    - uses: Randomblock1/theos-action@v1
      with:
        orion: 'false'

    - name: Install Pyzule
      run: |
        bash -c "$(curl https://raw.githubusercontent.com/asdfzxcvbn/pyzule/main/install-pyzule.sh)"

    - name: Compile Tweaks
      run: |
        cd Tweaks
        for tweak in */; do
          echo "Compiling $tweak"
          cd "$tweak"
          rm -f packages/*
          make package FINALPACKAGE=1
          echo "$tweak successfully compiled"
          cd ..
        done

    - name: Get os info
      run: sysctl -a | grep machdep.cpu
