name: YT Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install pyzule
      run: |
        bash -c "$(curl https://raw.githubusercontent.com/asdfzxcvbn/pyzule/main/install-pyzule.sh)"

    - name: Compile plugins
      run: |
        cd Tweaks
        

    - name: Pyzule
      run: pyzule-gen

    - name: Get os info
      run: sysctl -a | grep machdep.cpu
