name: YT Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Check cache
      run: |
        echo upstream_heads=$(git ls-remote https://github.com/theos/theos | head -n 1 | cut -f 1)-$(git ls-remote https://github.com/theos/sdks | head -n 1 | cut -f 1) >> $GITHUB_ENV

    - name: Use cache
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/theos
        key: ${{ runner.os }}-${{ env.upstream_heads }}
    
    - name: Prepare Theos
      uses: Randomblock1/theos-action@v1
      with:
        orion: 'false'
    
    - name: Prepare app headers
      run: |
        openssl rand -base64 12
        if [ ! -d "$THEOS/include/YouTubeHeader" ]; then
          echo "Installing app headers..."
          git clone https://github.com/PoomSmart/YouTubeHeader
          cp -r YouTubeHeader "$THEOS/include/"
          rm -r YouTubeHeader
        else
          echo "Headers already installed as theos libs."
        fi

    - name: Compile Tweaks
      run: |
        cd Tweaks
        for tweak in */; do
          echo "Compiling $tweak"
          cd "$tweak"
          git submodule update --init --recursive
          rm -f packages/*
          make package FINALPACKAGE=1
          echo "$tweak successfully compiled"
          cd ..
        done

    - name: Install pyzule
      run: bash -c "$(curl https://raw.githubusercontent.com/asdfzxcvbn/pyzule/main/install-pyzule.sh)"
    
    - name: Download base IPA
      run: wget -O base.ipa https://starfilesdl.com/279ae94974eb
    
    - name: Injection and patching process
      run: |
        patch_command="pyzule -i base.ipa -f"
        cd Tweaks
        for tweak in */; do
          cd "$tweak"
          cd packages
          for tweak_file in *; do
            patch_command="$patch_command Tweaks/$tweak/packages/$tweak_file"
          done
          cd ..
          cd ..
        done
        cd ..
        cd CompiledTweaks
        for compiledt in *; do
          patch_command="$patch_command CompiledTweaks/$compiledt"
        done
        cd ..
        cd Extensions
        for ext in */; do
          patch_command="$patch_command Extensions/$ext"
        done
        cd ..
        patch_command="$patch_command -o patched.ipa"
        $patch_command
        echo "Injection done!"

    - name: Upload ipa
      run: |
        rand_name=$(openssl rand -hex 9 | base64 | tr -dc 'a-zA-Z0-9')
        echo "$rand_name"
        mv patched.ipa "${rand_name}.ipa"
        pip install starfiles
        $PYTHON upload.py "{$rand_name}.ipa"
        echo "All done!"